# Makefile for tdisplay
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = main.o display.o
OUTPUT = tdisplay
LIBS=-lrterm.1 -lecho.1 -lmsg.1 -lsys.1 -lradar.1 -lgen.1 -ltermlib
include $(MAKEBIN)






  


