# Makefile for integratesgc214 library
# ==================================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4

SRC = pulsesgc214.c pulsesgc214.h integratesgc214.c
OBJS = pulsesgc214.o integratesgc214.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = integratesgc214
include $(MAKELIB)








 

 















