# Makefile for make_cmp
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_smr.o
OUTPUT = make_smr
LIBS=-lfit.1 -lsmr.1 -lradar.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





