# Makefile for ad library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radarqnx4
LINK="1"
SRC = ad.c dma-addr.c

OBJS = ad.o dma-addr.o 
DSTPATH=$(LIBPATH)
OUTPUT = ad
include $(MAKELIB)








 

 















