# Makefile for msg library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = freq_lib.o
LINK="1"
OUTPUT = freq
include $(MAKELIB)








 

 















