# Makefile for msg library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
SRC=decode_msg.c task_write.c log_error.c
OBJS = decode_msg.o task_write.o log_error.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = msg
include $(MAKELIB)








 

 















