# Makefile for fclr library
# ========================= 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4
SRC=fclrset.c fclrbase.c fclrfine.c fclr.c dcoffset.c
OBJS = fclrset.o fclrbase.o fclrfine.o fclr.o dcoffset.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = fclr
include $(MAKELIB)








 

 















