# Makefile for alter library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = radar_shell.o
LINK="1"
OUTPUT = rs
include $(MAKELIB)








 

 















