# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn

OBJS = fit_open.o fit_read.o fit_scan.o fit_close.o fit_write.o fit_seek.o \
       fit_read_inx.o fit_read_current.o
LINK="1"
OUTPUT = fit
include $(MAKELIB)


 

 















