# Makefile for make_fit
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = meteor_proc.o math.o nrutil.o
SRC=meteor_proc.c math.c 
#VERSION=1
OUTPUT = $(BINPATH)/meteor_proc
LIBS=-lfit.1 -lradar.1 -lgen.1 -laacgm.1
SLIB=-lm
include $(MAKEBIN)
 





