# Makefile for echoraw
# ==================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radarqnx4
SRC=echoraw.c taskname.h
OBJS = echoraw.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = echoraw
include $(MAKELIB)

