# Makefile for data_feed
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn \
		-I$(IPATH)/superdarn/fit -I$(IPATH)/radar \
        -I$(IPATH)/radar/int_lib \
        -I$(IPATH)/radar/fclr_lib \
		-I$(USR_IPATH)/ops
LINK="1"
OBJS = test_reopen.o setup.o tmseq.o fclr.o radar.o global.o shell.o \
       build_raw.o read_data.o calc_skip.o wait_boundary.o get_status.o \
       read_uconts.o init_proxy.o smr_control.o 
OUTPUT = ops
LIBPATH=$(USR_LIBPATH)
include $(MAKELIB)








 

 


















  









  


 


