# Makefile for site library
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar \
	-I$(USR_IPATH)/ops -I$(USR_IPATH)/site.f
SRC=site.c
OBJS = site.o
OUTPUT = f.site
LINK=1
DSTPATH=$(USR_LIBPATH)
include $(MAKELIB)


