# Makefile for data_feed
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn \
		-I$(IPATH)/superdarn/fit -I$(IPATH)/radar \
        -I$(IPATH)/radar/int_lib \
        -I$(IPATH)/radar/fclr_lib \
	-I$(USR_IPATH)/ops $(USR_IPATH)/site
SRC=site.c
OBJS = site.o
OUTPUT = site
LINK=1
LIBPATH=$(USR_LIBPATH)
include $(MAKELIB)








 

 


















  









  


 


