# Makefile for driver library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
LINK="1"
OBJS = a_d_drive.o dma-addr.o

OUTPUT = ad
include $(MAKELIB)








 

 















