# Makefile for msg library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = make_tsg.o check_tsg.o
LINK="1"
OUTPUT = tsg
include $(MAKELIB)








 

 















