# Makefile for fio library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/radarqnx4
SRC=fio.c
OBJS = fio.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = fio
include $(MAKELIB)








 

 















