# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
SRC = fit_open.c fit_read.c fit_scan.c fit_close.c fit_write.c fit_seek.c \
       fit_read_inx.c fit_read_current.c      
OBJS = fit_open.o fit_read.o fit_scan.o fit_close.o fit_write.o fit_seek.o \
       fit_read_inx.o fit_read_current.o
LINK="1"
OUTPUT = fit
include $(MAKELIB)


 

 















