# Makefile for taskid library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radar
SRC=taskid.c
OBJS = taskid.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = taskid
include $(MAKELIB)








 

 















