# Makefile for server
# ===================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = msg_io.o msg_mem.o connect.o socket.o cmp_fit.o \
			  fork.o transmit.o server.o

OUTPUT = server
LIBS=-lecho.1 -lmsg.1 -lsys.1 -lradar.1 -lgen.1
SLIB=-lsocket
include $(MAKEBIN)









 

