# Makefile for gridfit
# ====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar 
OBJS= process_beam.o gridfit.o 
SRC=process_beam.c gridfit.c
VERSION=1
OUTPUT = gridfit
LIBS=-lecho.1 -lmsg.1 -lsys.1 -lgrd.1 -lflt.1 -lradar.1 -lgen.1 -laacgm.1 -ligrf.1
include $(MAKEBIN)






  









 