# Makefile for dio library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radar
SRC=dio.c
OBJS = dio.o 
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = dio
include $(MAKELIB)








 

 















