# Makefile for radarshell library
# =============================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radarqnx4
SRC = radarshell.c taskname.h
OBJS = radarshell.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = rs
include $(MAKELIB)








 

 















