# Makefile for radar_test
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = test_radar.o help.o do_op.o read_tsg.o do_tsg.o
OUTPUT = test_radar
LIBS=-lad.1 -ldio.1 -lsys.1 -lgen.1
include $(MAKEBIN)
 







