# Makefile for integrate library
# ============================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radar

SRC = pulse.c pulse.h integrate.c
OBJS = pulse.o integrate.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = integrate
include $(MAKELIB)








 

 















