# Makefile for compress
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = compress.o
SRC=compress.c
VERSION=1
OUTPUT = compress
LIBS=-lecho.1 -lmsg.1 -lsys.1 -lcmp.1 -lradar.1 -lgen.1
include $(MAKEBIN)






  







