# Makefile for alter library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
SRC = radar_shell.c
OBJS = radar_shell.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = rs
include $(MAKELIB)








 

 















