# Makefile for fclr library
# ========================= 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = fclr_set.o fclr.o base_fclr.o fine_fclr.o sum_product.o
LINK="1"
OUTPUT = fclr
include $(MAKELIB)








 

 















