# Makefile for make_fit
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_fit.o
SRC=make_fit.c
VERSION=1
OUTPUT = make_fit
LIBS=-lfitacf.1 -lraw.1 -lfit.1 -lradar.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





