# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
SRC = cmp_open.c cmp_close.c cmp_read.c cmp_write.c cmp_scan.c fit_cmp.c \
       cmp_seek.c radar_cmp.c   
OBJS = cmp_open.o cmp_close.o cmp_read.o cmp_write.o cmp_scan.o fit_cmp.o \
       cmp_seek.o radar_cmp.o 
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = cmp
include $(MAKELIB)


 

 















