# Makefile for rtimer library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/radarqnx4
LINK="1"
SRC = rtimer.c
OBJS = rtimer.o 
DSTPATH=$(LIBPATH)
OUTPUT = rtimer
include $(MAKELIB)








 

 















