# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn

OBJS = raw_write.o raw_open.o raw_close.o raw_read.o raw_seek.o \
       raw_read_current.o

OUTPUT = raw
LINK="1"
include $(MAKELIB)


 

 















