# Makefile for make_smr
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_smr.o
SRC=make_smr.c
VERSION=1
OUTPUT = $(BINPATH)/make_smr
LIBS=-lfit.1 -lsmr.1 -lradar.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





