# Makefile for aacgm library
# ==========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general
OBJS = math.o aacgm.o altitude_to_cgm.o cgm_to_altitude.o coeff.o \
       convert_geo_coord.o eqn_of_time.o mlt.o mlt1.o rylm.o \
       solar_loc.o
LINK="1"
OUTPUT = aacgm
include $(MAKELIB)

 

 





