# Makefile for master library
# =========================== 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/superdarn/filter
OBJS = filter.o error.o check_ops.o middle.o bound.o
LINK="1"
OUTPUT = flt
include $(MAKELIB)
 

 





