# Makefile for integratesgc214 library
# ==================================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4
IGNVER=1
SRC = pulse.c pulse.h integratesgc214ex.c
OBJS = pulse.o integratesgc214ex.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = integratesgc214ex
include $(MAKELIB)








 

 















