# Makefile for site library
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn \
        -I$(IPATH)/radarqnx4 -I$(USR_IPATH)/radarqnx4/ops -I$(USR_IPATH)/radarqnx4/site.${SD_RADARCODE}

SRC=interface.c hdw.c tmseq.c globals.c builds.c 
OBJS = interface.o hdw.o tmseq.o globals.o builds.o

OUTPUT = site.${SD_RADARCODE}
LINK=1
DSTPATH=$(USR_LIBPATH)
include $(MAKELIB)








 

 


















  









  


 


