# Makefile for cat_fit
# ====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = trim_fit.o
SRC=trim_fit.c
VERSION=1
OUTPUT = $(BINPATH)/trim_fit
LIBS=-lfit.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





