# Makefile for make_cmp
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_cmp.o
SRC=make_cmp.c
VERSION=1
OUTPUT = $(BINPATH)/make_cmp
LIBS=-lfit.1 -lcmp.1  -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





