# Makefile for msg library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

SRC  = make_tsg.c check_tsg.c
OBJS = make_tsg.o check_tsg.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = tsg
include $(MAKELIB)








 

 















