# Makefile for fclrgc214 library (GC214 Digital Receiver FCLR) 
# ============================================================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radar

SRC = fclrgc214.c
OBJS = fclrgc214.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = fclrgc214
include $(MAKELIB)








 

 















