# Makefile for make_vec
# =====================
# by R.J.Barnes
#
#
 
INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn 
OBJS = make_vec.o

OUTPUT = make_vec
LIBS=-lgrd.1 -lradar.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN) 

 





