# Makefile for integrate library
# ============================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4

SRC = pulses.c pulses.h integrates.c
OBJS = pulses.o integrates.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = integrates
include $(MAKELIB)








 

 















