#  Makefile for gsm library
#  ========================

INCLUDE=-I$(IPATH)/general
OBJS = matcald.o crdnt.o cnv_geo_gsm.o cnv_gse_gsm.o cnv_gsm_geo.o \
       cnv_gsm_gse.o cnv_gsm_sm.o
OUTPUT = gsm
LINK="1"
include $(MAKELIB)


 















