# Makefile for echo library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radar
SRC=echo.c taskname.h
OBJS = echo.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = echo
include $(MAKELIB)








 

 















