# Makefile for sys library
# ======================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = file_io.o message.o test_key.o timer.o
LINK="1"
OUTPUT = sys
include $(MAKELIB)








 

 















