# Makefile for tcpipmsg library
# ============================ 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radarqnx4
LINK="1"
SRC = tcpipmsg.c
OBJS = tcpipmsg.o 
DSTPATH=$(LIBPATH)
OUTPUT = tcpipmsg
include $(MAKELIB)








 

 















