# Makefile for task_reset
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = task_kill.o
SRC=task_kill.c
VERSION=1
OUTPUT = task_kill
LIBS=-lmsg.1 -lsys.1 -lradar.1 -lgen.1
include $(MAKEBIN)










  








 


