# Makefile for AACGMConvertMLT
# ============================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/analysis 
OBJS = AACGMConvertMLT.o
OUTPUT = AACGMConvertMLT
LIBS= -laacgm.1 -lrtime.1
SLIB=-lm
include $(MAKEBIN)
 





