# Makefile for ACFex library
# ========================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4

SRC = acfex.c 
OBJS = acfex.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = acfex
include $(MAKELIB)








 

 















