# Makefile for dio library
# ======================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = dio.o 
LINK="1"
OUTPUT = dio
include $(MAKELIB)








 

 















