# Makefile for site library
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn \
        -I$(IPATH)/radarqnx4 -I$(USR_IPATH)/radarqnx4/ops -I$(USR_IPATH)/radarqnx4/site.${SD_RADARCODE}

SRC=globals.c interface.c hdw.c builds.c tmseq.c 
OBJS = globals.o interface.o hdw.o builds.o tmseq.o
OUTPUT = site.${SD_RADARCODE}
LINK=1
DSTPATH=$(USR_LIBPATH)
include $(MAKELIB)








 

 


















  









  


 


