# Makefile for fclrgcs214 library (GC214TS Digital Receiver FCLR) 
# ===============================================================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4
SRC = fclrsgc214.c
OBJS = fclrsgc214.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = fclrsgc214
include $(MAKELIB)








 

 















