# Makefile for radar_shell
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = main.o shell.o
SRC=main.c shell.c
VERSION=0
LIBS=-lgen.1
OUTPUT = $(BINPATH)/stereoserver
include $(MAKEBIN)
