# Makefile for rmsgrcv library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radarqnx4
SRC=rmsgrcv.o
OBJS = rmsgrcv.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = rmsgrcv
include $(MAKELIB)








 

 















