# Makefile for trim_raw
# =====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = trim_raw.o
SRC=trim_raw.c
VERSION=1
OUTPUT = $(BINPATH)/trim_raw
LIBS=-lraw.1 -lradar.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





