# Makefile for cat_fit
# ====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_inx.o
SRC=make_inx.c
VERSION=1
OUTPUT = $(BINPATH)/make_inx
LIBS=-lfit.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





