# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn

OBJS = smr_read.o smr_seek.o smr_scan.o smr_write.o 

OUTPUT = smr
LINK="1"
include $(MAKELIB)


 

 















