# Makefile for msg library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = decode_msg.o task_write.o log_error.o
LINK="1"
OUTPUT = msg
include $(MAKELIB)








 

 















