# Makefile for gc214 library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radarqnx4
LINK="1"
SRC = gc214.c dma-addr.c
OBJS = gc214.o dma-addr.o
DSTPATH=$(LIBPATH)
OUTPUT = gc214
include $(MAKELIB)








 

 















