# Makefile for raw_write
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = raw_write.o
SRC=raw_write.c
VERSION=1
OUTPUT = raw_write
LIBS=-lmsg.1 -lsys.1 -lraw.1 -lradar.1 -lgen.1
include $(MAKEBIN)






  


