# Makefile for phase library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
SRC = acf.c sum_power.c normalize_baud.c phase_decode.c phase.c
OBJS = acf.o sum_power.o normalize_baud.o phase_decode.o phase.o
LINK="1"
OUTPUT = phase
include $(MAKELIB)








 

 















