# Makefile for rawfeed library
# ============================ 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4
LINK="1"
SRC = rawfeed.c
OBJS = rawfeed.o 
DSTPATH=$(LIBPATH)
OUTPUT = rawfeed
include $(MAKELIB)








 

 















