# Makefile for data_feed
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn \
		-I$(IPATH)/superdarn/fit -I$(IPATH)/radar \
        -I$(IPATH)/radar/int_lib \
        -I$(IPATH)/radar/fclr_lib \
		-I$(USR_IPATH)/ops_s
LINK="1"
OBJS = do_pulse_s.o do_radar_s.o radar_s.o global_s.o tmseq_s.o setup.o \
       get_status_s.o shell_s.o build_raw_s.o read_data_s.o  \
       calc_skip.o init_proxy.o test_reopen.o wait_boundary.o \
       read_uconts.o fclr_s.o base_fclr_s.o do_fclr_s.o

OUTPUT = ops_s
LIBPATH=$(USR_LIBPATH)
include $(MAKELIB)








 

 


















  









  


 


