# Makefile for data_feed
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn \
		-I$(IPATH)/radar
OBJS = data_feed.o
OUTPUT = data_feed
LIBS=-lmsg.1 -lsys.1 -lradar.1 -lfit.1 -lraw.1 -lfitacf.1 -lgen.1
include $(MAKEBIN)






  









  


 


