#  Makefile for mktsg
#  ==================

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4 
SRC = mktsg.c 
OBJS = mktsg.o 
OUTPUT = $(BINPATH)/mktsg
LIBS= -ltsg.1 -lopt.1
include $(MAKEBIN)

