# Makefile for monitor library
# ============================ 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radar
LINK="1"
SRC = monitor.c

OBJS = monitor.o 
DSTPATH=$(LIBPATH)
OUTPUT = monitor
include $(MAKELIB)








 

 















