# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn

OBJS = cmp_open.o cmp_close.o cmp_read.o cmp_write.o cmp_scan.o fit_cmp.o \
       cmp_seek.o radar_cmp.o
LINK="1"
OUTPUT = cmp
include $(MAKELIB)


 

 















