# Makefile for echo library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
SRc=echo_util.c
OBJS = echo_util.o
LINK="1"
OUTPUT = echo
include $(MAKELIB)








 

 















