# Makefile for master library
# =========================== 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/superdarn/grid
OBJS = gtable.o write_gtable.o read_grid.o write_grid.o \
       merge_grid.o avg_grid.o
LINK="1"
OUTPUT = grd
include $(MAKELIB)
 

 





