# Makefile for task_reset
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = task_reset.o
SRC=task_reset.c
VERSION=1
OUTPUT = $(BINPATH)/task_reset
LIBS=-lmsg.1 -lsys.1 -lradar.1 -lgen.1
include $(MAKEBIN)










  








 


