# Makefile for integrategc214 library (GC214 Digital Receiver Integration) 
# ========================================================================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radar

SRC = pulse.c pulse.h integrategc214.c
OBJS = pulse.o integrategc214.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = integrategc214
include $(MAKELIB)








 

 















