# Makefile for rmsgsnd library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/radarqnx4
SRC=rmsgsnd.c 
OBJS = rmsgsnd.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = rmsgsnd
include $(MAKELIB)








 

 















