# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
SRC = smr_read.c smr_seek.c smr_scan.c smr_write.c

OBJS = smr_read.o smr_seek.o smr_scan.o smr_write.o 

OUTPUT = smr
LINK="1"
include $(MAKELIB)


 

 















