#!/bin/sh
# $Log: rpkg,v $
# Revision 1.1  2004/06/15 15:18:57  barnes
# Initial revision
#

fname=$1
rm -f .setup
rm -f .message
gunzip -c $fname | tar -xvf -

if test -f .message                                                            
  then                                                                         
    cat .message
    rm -f .message                                                             
  fi 
if test -x .setup 
  then
    ./.setup
    rm -f .setup
  fi



