# Makefile for data_feed
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn \
		-I$(IPATH)/superdarn/fit -I$(IPATH)/radar \
        -I$(USR_IPATH)/ops -I$(USR_IPATH)/site
OBJS = fast_scan.o
SRC=fast_scan.c
SUDO=1
OUTPUT = fast_scan
BINPATH=$(USR_BINPATH)
LIBS= -lsite.1 -lops.1 -lrs.1 -lfclr.1 -lint.1 -lfreq.1 -lmsg.1 \
      -lsys.1 -lad.1 -ldio.1 -ltsg.1 -lraw.1 -lradar.1 -lfitacf.1 -lgen.1 
include $(MAKEBIN)






  









  


 


