# Makefile for gen_lib
# ====================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general
SRC =  cnv_time.c option.c read_clock.c cnv_data.c read_file.c \
        transform.c test_file.c print_info.c    
OBJS =  cnv_time.o option.o read_clock.o cnv_data.o read_file.o \
	transform.o test_file.o print_info.o 
LINK="1"
OUTPUT = gen
include $(MAKELIB)


 

 





