# Makefile for cat_fit
# ====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = cat_fit.o
SRC=cat_fit.c
VERSION=1
OUTPUT = $(BINPATH)/cat_fit
LIBS=-lfit.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





