# Makefile for int library
# ======================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = acf.o average.o normalize.o do_pulse.o sum_power.o badlag.o radar.o
LINK="1"
OUTPUT = int
include $(MAKELIB)








 

 















