# Makefile for fclrgc214TS library (GC214TS Digital Receiver FCLR) 
# ============================================================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4
SRC = fclrgc214TS.c
OBJS = fclrgc214TS.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = fclrgc214TS
include $(MAKELIB)








 

 















