# Makefile for scheduler
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = log_info.o load_schedule.o print_schedule.o set_schedule.o \
       test_schedule.o check_program.o refresh.o execute.o main.o 
SUDO=1
OUTPUT = schedule 
LIBS=-lgen.1
include $(MAKEBIN)






  





 