# Makefile for scheduler
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = log_info.o load_schedule.o print_schedule.o set_schedule.o \
       test_schedule.o check_program.o refresh.o execute.o main.o 
SRC = log_info.c load_schedule.c print_schedule.c set_schedule.c \
       test_schedule.c check_program.c refresh.c execute.c main.c 

VERSION=1
SUDO=1
OUTPUT = $(BINPATH)/schedule 
LIBS=-lgen.1
include $(MAKEBIN)






  





 