# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
SRC = raw_write.c raw_open.c raw_close.c raw_read.c raw_seek.c \
       raw_read_current.c       
OBJS = raw_write.o raw_open.o raw_close.o raw_read.o raw_seek.o \
       raw_read_current.o

OUTPUT = raw
LINK="1"
include $(MAKELIB)


 

 















