# Makefile for msg library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
SRC=freq_lib.c
OBJS = freq_lib.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = freq
include $(MAKELIB)








 

 















