# Makefile for errlog library
# =========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radar
SRC=errlog.c
OBJS=errlog.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = errlog
include $(MAKELIB)








 

 















