# Makefile for sd_summary
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = sd_summary.o
OUTPUT = sd_summary
LIBS=-lecho.1 -lmsg.1 -lsys.1 -lsmr.1 -lradar.1 -lgen.1
include $(MAKEBIN)






  


