# Makefile for echo_data
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = echo.o
SRC=echo.c
VERSION=1
OUTPUT = $(BINPATH)/echo_data
LIBS=-lsys.1 -lmsg.1 -lradar.1 -lgen.1
include $(MAKEBIN)






  







 


