#  Makefile for igrf library
#  ========================

INCLUDE=-I$(IPATH)/general
OBJS = shval3.o dihf.o interpshc.o extrapshc.o magcmp.o igrfcall.o getshc.o
OUTPUT = igrf
LINK="1"
include $(MAKELIB)


 















