# Makefile for fclrs library
# ========================= 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4
SRC=fclrsbase.c  fclrs.c 
OBJS = fclrsbase.o fclrs.o 
LINK="1"
IGNVER=1
DSTPATH=$(LIBPATH)
OUTPUT = fclrs
include $(MAKELIB)








 

 















