# Makefile for dio library
# ======================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
SRC=dio.c
OBJS = dio.o 
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = dio
include $(MAKELIB)








 

 















