# Makefile for radar library
# ========================== 
# by R.J.Barnes
#


INCLUDE=-I$(IPATH)/general -I$(IPATH)/analysis -I$(IPATH)/superdarn 
SRC = cnvt_coord.c inv_mag.c hardware.c radar_name.c radar_scan.c  
OBJS = cnvt_coord.o inv_mag.o hardware.o radar_name.o radar_scan.o 
DSTPATH=$(LIBPATH)
OUTPUT = radar
LINK="1"
include $(MAKELIB)


 

 















