# Makefile for site library
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn \
        -I$(IPATH)/radar -I$(USR_IPATH)/radar -I$(USR_IPATH)/site.${SD_RADARCODE}
SRC=interface.c hdw.c tmseq.c 
OBJS = interface.o hdw.o tmseq.o
OUTPUT = site.${SD_RADARCODE}
LINK=1
DSTPATH=$(USR_LIBPATH)
include $(MAKELIB)








 

 


















  









  


 


