# Makefile for shmem library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/radarqnx4
SRC=shmem.c
OBJS = shmem.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = shmem
include $(MAKELIB)








 

 















