# Makefile for site library
# =========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn \
		-I$(IPATH)/superdarn/fit -I$(IPATH)/radar \
        -I$(IPATH)/radar/int_lib \
        -I$(IPATH)/radar/fclr_lib \
	-I$(USR_IPATH)/ops -I$(USR_IPATH)/site.n
SRC=site.c
OBJS = site.o
OUTPUT = n.site
LINK=1
DSTPATH=$(USR_LIBPATH)
include $(MAKELIB)








 

 


















  









  


 


