# Makefile for radar_test
# =======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = test_radar.o help.o do_op.o read_tsg.o do_tsg.o
SRC=test_radar.c help.c do_op.c read_tsg.c do_tsg.c
VERSION=1
OUTPUT = $(BINPATH)/test_radar
LIBS=-lad.1 -ldio.1 -lsys.1 -lgen.1
include $(MAKEBIN)
 







