# Makefile for ACF library
# ========================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 
SRC = iqcopy.c 
OBJS = iqcopy.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = iqcopy
include $(MAKELIB)