# Makefile for master library
# =========================== 
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/superdarn/grid
SRC = gtable.c write_gtable.c read_grid.c write_grid.c \
       merge_grid.c avg_grid.c integrate_grid.c add_grid.c sort_grid.c \
       copy_grid.c   
OBJS = gtable.o write_gtable.o read_grid.o write_grid.o \
       merge_grid.o avg_grid.o integrate_grid.o add_grid.o sort_grid.o \
       copy_grid.o
 
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = grd
include $(MAKELIB)
 

 





