/* filer_def.h
   =========== */

#define FILER_WIDTH 32
#define FILER_HEIGHT 16
#define FILER_ATTR TERM_RED
#define FILER_BOT_ATTR TERM_WHITE
#define FILER_BOT_CRS_ATTR TERM_WHITE | TERM_INVERSE
#define FILER_TOP_ATTR TERM_WHITE
#define FILER_TOP_CRS_INS_ATTR TERM_WHITE | TERM_INVERSE
#define FILER_TOP_CRS_OVR_ATTR TERM_GREEN | TERM_INVERSE
