# Makefile for rterm library 
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar

OBJS = filer.o terminal.o
LINK="1"
OUTPUT = rterm
include $(MAKELIB)








 

 















