#!/bin/sh
find ~/* -follow -name "*.o" -exec rm -fv {} \;
find ~/* -follow -name "*.err" -exec rm -fv {} \;
find ~/* -follow -name "*~" -exec rm -fv {} \;
find ~/* -follow -name "#*#" -exec rm -fv {} \;













