# Makefile for radar_shell
# ========================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = main.o shell.o
LIBS=-lgen.1
OUTPUT = radar_shell
include $(MAKEBIN)
