# Makefile for freq library
# ========================== 
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/radar
SRC=freq.c
OBJS = freq.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = freq
include $(MAKELIB)








 

 















