# Makefile for aacgm library
# ==========================
# by R.J.Barnes
#
#
INCLUDE=-I$(IPATH)/general

SRC = math.c aacgm.c altitude_to_cgm.c cgm_to_altitude.c coeff.c \
       convert_geo_coord.c eqn_of_time.c mlt.c mlt1.c rylm.c \
       solar_loc.c    
OBJS = math.o aacgm.o altitude_to_cgm.o cgm_to_altitude.o coeff.o \
       convert_geo_coord.o eqn_of_time.o mlt.o mlt1.o rylm.o \
       solar_loc.o
DSTPATH=$(LIBPATH)
LINK="1"
OUTPUT = aacgm
include $(MAKELIB)

 

 





