# Makefile for data_feed
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn \
		-I$(IPATH)/superdarn/fit -I$(IPATH)/radar \
        -I$(USR_IPATH)/s_ops -I$(USR_IPATH)/site.$(ST_RADARCODE)
OBJS = stereo_scan.o 
SRC=stereo_scan.c
OUTPUT = $(USR_BINPATH)/stereo_scan
SUDO = 1 
VERSION=1

LIBS=-lops_s.1 -lrs.1 -lfclr.1  -lint.1 -lfreq.1 -lmsg.1 -lsys.1 -lad.1 -ldio.1 -ltsg.1 -lraw.1 -lradar.1 -lfitacf.1 -lgen.1 
include $(MAKEBIN)






  









  


 


