#  Makefile for igrf library
#  ========================

INCLUDE=-I$(IPATH)/general
SRC=shval3.c dihf.c interpshc.c extrapshc.c magcmp.c igrfcall.c getshc.c  
OBJS = shval3.o dihf.o interpshc.o extrapshc.o magcmp.o igrfcall.o getshc.o
SRC = shval3.c dihf.c interpshc.c extrapshc.c magcmp.c igrfcall.c getshc.c
DSTPATH=$(LIBPATH)
OUTPUT = igrf
LINK="1"
include $(MAKELIB)


 















