# Makefile for fit_write
# ======================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radar
OBJS = fit_write.o
OUTPUT = fit_write
LIBS=-lmsg.1 -lsys.1 -lfit.1 -lradar.1 -lgen.1
include $(MAKEBIN)




