# Makefile for cat_fit
# ====================
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = cat_raw.o
SRC=cat_raw.c
VERSION=1
OUTPUT = cat_raw
LIBS=-lraw.1 -lradar.1 -lgen.1 
SLIB=-lm
include $(MAKEBIN)
 





