# Makefile for integrategc214ex library (GC214 Digital Receiver Integration) 
# ==========================================================================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/radarqnx4

SRC = pulse.c pulse.h integrategc214ex.c
OBJS = pulse.o integrategc214ex.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = integrategc214ex
include $(MAKELIB)








 

 















